# .github/workflows/terraform.yml

name: "Terraform Google Cloud VM"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'

    steps:
      # Passo 1: Checar o código
      - name: "Checkout code"
        uses: actions/checkout@v4


      # Passo 2: Configurar o Google Cloud CLI
      - name: "Set up Google Cloud"
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }} # Ensure this secret is set in your repository settings

      # Passo 3: Instalar o Terraform
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Passo 4: Inicializar o Terraform
      - name: "Terraform Init"
        run: cd ./terraform/main && terraform init

      # # Passo 5: Verificar o plano do Terraform
      # - name: "Terraform Plan"
      #   run: terraform plan

      # Passo 6: Aplicar as mudanças do Terraform (com aprovação manual)
      - name: "Terraform Apply"
        run: cd ./terraform/main && terraform apply -var-file="terraform.tfvars" -auto-approve -debug
        
